name: Continuous Integration

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linting tools
        run: |
          pip install flake8 black isort
        timeout-minutes: 2

      - name: Run flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics \
            --exclude=venv,env,.venv,.git,__pycache__,experiments

      - name: Check code formatting (black)
        run: |
          black --check . --exclude='/(\.git|\.venv|venv|env|__pycache__|experiments)/'
        continue-on-error: true

      - name: Check import sorting (isort)
        run: |
          isort . --check-only --skip venv --skip .venv --skip env
        continue-on-error: true

      - name: Validate Python syntax
        run: |
          python -m compileall . -q
        continue-on-error: true

  validate-requirements:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check requirements.txt
        run: |
          if [ -f requirements.txt ]; then
            echo "✅ requirements.txt found"
            pip install --dry-run -r requirements.txt 2>&1 | head -20 || true
          else
            echo "❌ requirements.txt not found"
            exit 1
          fi